package Formularios;

import javax.swing.JOptionPane;

public class FrmMenu extends javax.swing.JFrame {
    FrmLogin login=new FrmLogin();

    public FrmMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        login.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem30 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenu14 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        escritorio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClientes = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuDemandados = new javax.swing.JMenu();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuEstado = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuAsunto = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuLugares = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuAbogado = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuAudiencia = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuResolucion = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuPersonas = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMasOpciones = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenuItem55 = new javax.swing.JMenuItem();
        jMenuItem42 = new javax.swing.JMenuItem();
        jMenuItem43 = new javax.swing.JMenuItem();
        jMenuItem44 = new javax.swing.JMenuItem();
        jMenuItem45 = new javax.swing.JMenuItem();
        jMenuItem46 = new javax.swing.JMenuItem();
        jMenuItem47 = new javax.swing.JMenuItem();
        jMenuItem48 = new javax.swing.JMenuItem();
        jMenuItem49 = new javax.swing.JMenuItem();
        jMenuItem50 = new javax.swing.JMenuItem();
        jMenuItem51 = new javax.swing.JMenuItem();
        jMenuItem52 = new javax.swing.JMenuItem();
        jMenuItem53 = new javax.swing.JMenuItem();
        jMenuItem54 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenuItem30.setText("jMenuItem30");

        jLabel1.setText("jLabel1");

        jMenu14.setText("jMenu14");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        escritorio.setBackground(new java.awt.Color(255, 255, 255));
        escritorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen2.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("BIENVENIDO AL SISTEMA  \"BUFETE DE ABOGADOS\"");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("USUARIO:");

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1370, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(272, 272, 272)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuClientes.setForeground(new java.awt.Color(0, 102, 102));
        jMenuClientes.setText("Clientes");
        jMenuClientes.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem1.setText("Agregar nuevo cliente");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItem1);

        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem6.setText("Buscar Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenuClientes.add(jMenuItem6);

        jMenuBar1.add(jMenuClientes);

        jMenuDemandados.setForeground(new java.awt.Color(0, 102, 102));
        jMenuDemandados.setText("Demandados");
        jMenuDemandados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem33.setText("Añadir  Tipo");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenuDemandados.add(jMenuItem33);

        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem3.setText("Mostrar datos de demandados registrados");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenuDemandados.add(jMenuItem3);

        jMenuItem34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem34.setText("Registrar datos demandado");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenuDemandados.add(jMenuItem34);

        jMenu13.setText("Personas demandadas físicas");
        jMenu13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem7.setText("Registrar Nueva");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem7);

        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem8.setText("Consultar Registros");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem8);

        jMenuDemandados.add(jMenu13);

        jMenu15.setText("Personas morales o empresas demandadas");
        jMenu15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem16.setText("Registrar Nueva");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem16);

        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem9.setText("Consultar Registros");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem9);

        jMenuDemandados.add(jMenu15);

        jMenuBar1.add(jMenuDemandados);

        jMenuEstado.setForeground(new java.awt.Color(0, 102, 102));
        jMenuEstado.setText("Estados");
        jMenuEstado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstadoActionPerformed(evt);
            }
        });

        jMenuItem12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem12.setText("Agregar Estado");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenuEstado.add(jMenuItem12);

        jMenuBar1.add(jMenuEstado);

        jMenuAsunto.setForeground(new java.awt.Color(0, 102, 102));
        jMenuAsunto.setText("Asuntos");
        jMenuAsunto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem2.setText("Registrar tipo de Asuntos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuAsunto.add(jMenuItem2);

        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem14.setText("Registrar asunto");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenuAsunto.add(jMenuItem14);

        jMenuBar1.add(jMenuAsunto);

        jMenuLugares.setForeground(new java.awt.Color(0, 102, 102));
        jMenuLugares.setText("Oficinas");
        jMenuLugares.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem15.setText("Añadir lugar");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenuLugares.add(jMenuItem15);

        jMenuBar1.add(jMenuLugares);

        jMenuAbogado.setForeground(new java.awt.Color(0, 102, 102));
        jMenuAbogado.setText("Abogados");
        jMenuAbogado.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem17.setText("Registar nuevo");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenuAbogado.add(jMenuItem17);

        jMenuItem18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem18.setText("Ver registros de abogados");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenuAbogado.add(jMenuItem18);

        jMenuBar1.add(jMenuAbogado);

        jMenuAudiencia.setForeground(new java.awt.Color(0, 102, 102));
        jMenuAudiencia.setText("Audiencias");
        jMenuAudiencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem19.setText("Registro Audiencias");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenuAudiencia.add(jMenuItem19);

        jMenuBar1.add(jMenuAudiencia);

        jMenuResolucion.setForeground(new java.awt.Color(0, 102, 102));
        jMenuResolucion.setText("Resoluciones");
        jMenuResolucion.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem21.setText("Añadir y Ver Registros");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenuResolucion.add(jMenuItem21);

        jMenuBar1.add(jMenuResolucion);

        jMenuPersonas.setForeground(new java.awt.Color(0, 102, 102));
        jMenuPersonas.setText("Personas");
        jMenuPersonas.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenuItem23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem23.setText("Agregar nueva");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenuPersonas.add(jMenuItem23);

        jMenuItem24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem24.setText("Ver registros");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenuPersonas.add(jMenuItem24);

        jMenuItem25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem25.setText("Asignar a audiencia");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenuPersonas.add(jMenuItem25);

        jMenuBar1.add(jMenuPersonas);

        jMasOpciones.setForeground(new java.awt.Color(0, 102, 102));
        jMasOpciones.setText("Mas Opciones");
        jMasOpciones.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu12.setText("Auditorias");
        jMenu12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem35.setText("ABOGADOS");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem35);

        jMenuItem36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem36.setText("ASESORIAS");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem36);

        jMenuItem37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem37.setText("ASISTENCIA PERSONAS");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem37);

        jMenuItem38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem38.setText("ASUNTOS");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem38);

        jMenuItem39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem39.setText("ASUNTO ABOGADOS");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem39);

        jMenuItem40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem40.setText("AUDIENCIAS");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem40);

        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem4.setText("CLIENTES");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem4);

        jMenuItem41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem41.setText("DEMANDADOS");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem41);

        jMenuItem55.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem55.setText("EMAIL");
        jMenuItem55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem55ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem55);

        jMenuItem42.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem42.setText("EMPRESAS DEMANDADAS");
        jMenuItem42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem42ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem42);

        jMenuItem43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem43.setText("ESTADO");
        jMenuItem43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem43ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem43);

        jMenuItem44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem44.setText("FACEBOOK");
        jMenuItem44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem44ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem44);

        jMenuItem45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem45.setText("GRADOS ACADEMICOS");
        jMenuItem45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem45ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem45);

        jMenuItem46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem46.setText("LUGARES");
        jMenuItem46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem46ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem46);

        jMenuItem47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem47.setText("MEDIOS DE CONTACTO");
        jMenuItem47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem47ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem47);

        jMenuItem48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem48.setText("PERSONAS EN AUDIENCIAS");
        jMenuItem48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem48ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem48);

        jMenuItem49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem49.setText("PERSONAS DEMANDADAS");
        jMenuItem49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem49ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem49);

        jMenuItem50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem50.setText("RESOLUCIONES");
        jMenuItem50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem50ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem50);

        jMenuItem51.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem51.setText("TELEFONOS");
        jMenuItem51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem51ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem51);

        jMenuItem52.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem52.setText("TIPOS DE ASUNTO");
        jMenuItem52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem52ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem52);

        jMenuItem53.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem53.setText("TIPOS DE DEMANDADOS");
        jMenuItem53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem53ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem53);

        jMenuItem54.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem54.setText("TIPOS DE MEDIOS DE CONTACTO");
        jMenuItem54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem54ActionPerformed(evt);
            }
        });
        jMenu12.add(jMenuItem54);

        jMasOpciones.add(jMenu12);

        jMenuItem26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem26.setText("Asuntos y Abogados");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMasOpciones.add(jMenuItem26);

        jMenuItem28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem28.setText("Añadir asesoria de abogados");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMasOpciones.add(jMenuItem28);

        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem13.setText("Grados Académicos");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMasOpciones.add(jMenuItem13);

        jMenu16.setText("Medios de Contacto");
        jMenu16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem20.setText("Añadir nombre de medio de contacto");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem20);

        jMenuItem22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem22.setText("Buscar cliente por medio de contacto");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem22);

        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem10.setText("Registrar nuevo contacto a cliente");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem10);

        jMasOpciones.add(jMenu16);

        jMenu11.setText("Perfil de Usuario");
        jMenu11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem31.setText("Agregar nuevo usuario");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem31);

        jMenuItem32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem32.setText("Cambiar password");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem32);

        jMasOpciones.add(jMenu11);

        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuItem5.setText("Cerrar sesión");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMasOpciones.add(jMenuItem5);

        jMenuBar1.add(jMasOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
         int s = JOptionPane.showConfirmDialog(null, "¿ESTAS SEGURO QUE DESEAS SALIR DEL SISTEMA?", "CONFIRMACION", 0);
        if (s == 0) {
            JOptionPane.showMessageDialog(null, "¡¡HASTA PRONTO!!");
            this.dispose();
            FrmLogin login=new FrmLogin();
            login.setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrmRegistroClientes rc=new FrmRegistroClientes();
        escritorio.add(rc);
        rc.show();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrmClientesRegistrados fcr=new FrmClientesRegistrados();
        fcr.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        FrmTiposDemandado ftd=new FrmTiposDemandado();
        escritorio.add(ftd);
        ftd.show();
      
    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        FrmRegistroDemandado fd=new FrmRegistroDemandado();
        escritorio.add(fd);
        fd.show();
        
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        FrmAuditoriaClientes fraudclientes=new FrmAuditoriaClientes();
        escritorio.add(fraudclientes);
        fraudclientes.show();
       
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem51ActionPerformed
        FrmAuditoriaTelefono fraudtel=new FrmAuditoriaTelefono();
        escritorio.add(fraudtel);
        fraudtel.show();
    
    }//GEN-LAST:event_jMenuItem51ActionPerformed

    private void jMenuItem55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem55ActionPerformed
        FrmAuditoriaEmail fraudmail=new FrmAuditoriaEmail();
       escritorio.add(fraudmail);
       fraudmail.show();
       
    }//GEN-LAST:event_jMenuItem55ActionPerformed

    private void jMenuItem44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem44ActionPerformed
        FrmAuditoriaFacebook fraudface=new FrmAuditoriaFacebook();
        escritorio.add(fraudface);
        fraudface.show();
      
    }//GEN-LAST:event_jMenuItem44ActionPerformed

    private void jMenuItem54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem54ActionPerformed
        FrmAuditoriaTiposMedios fraudtm=new FrmAuditoriaTiposMedios();
        escritorio.add(fraudtm);
        fraudtm.show();
       
    }//GEN-LAST:event_jMenuItem54ActionPerformed

    private void jMenuItem47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem47ActionPerformed
        FrmAuditoriaMedioContacto fraudmc=new FrmAuditoriaMedioContacto();
        escritorio.add(fraudmc);
        fraudmc.show();
       
    }//GEN-LAST:event_jMenuItem47ActionPerformed

    private void jMenuItem53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem53ActionPerformed
        FrmAuditoriaTipoDemandado fraudtm=new FrmAuditoriaTipoDemandado();
        escritorio.add(fraudtm);
        fraudtm.show();
   
    }//GEN-LAST:event_jMenuItem53ActionPerformed

    private void jMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstadoActionPerformed
        
    }//GEN-LAST:event_jMenuEstadoActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
       FrmEstados frestados=new FrmEstados();
        escritorio.add(frestados);
        frestados.show();
       
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        FrmGradosAcademicos frmgrad=new FrmGradosAcademicos();
        escritorio.add(frmgrad);
        frmgrad.show();
      
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        FrmResoluciones frmres=new FrmResoluciones();
        escritorio.add(frmres);
        frmres.show();
       
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        FrmRegistroLugares frmlug=new FrmRegistroLugares();
        escritorio.add(frmlug);
        frmlug.show();
   
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrmRegistroTiposAsunto frmtpasunto=new FrmRegistroTiposAsunto();
        escritorio.add(frmtpasunto);
        frmtpasunto.show();
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem52ActionPerformed
        FrmAuditoriaTipoAsuntos frmaudtip=new FrmAuditoriaTipoAsuntos();
        escritorio.add(frmaudtip);
        frmaudtip.show();
        
    }//GEN-LAST:event_jMenuItem52ActionPerformed

    private void jMenuItem43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem43ActionPerformed
        FrmAuditoriaEstados frmaudtest=new FrmAuditoriaEstados();
        escritorio.add(frmaudtest);
        frmaudtest.show();
      
    }//GEN-LAST:event_jMenuItem43ActionPerformed

    private void jMenuItem45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem45ActionPerformed
        FrmAuditoriaGradosAcademicos frmaudgrad=new FrmAuditoriaGradosAcademicos();
        escritorio.add(frmaudgrad);
        frmaudgrad.show();
       
    }//GEN-LAST:event_jMenuItem45ActionPerformed

    private void jMenuItem46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem46ActionPerformed
        FrmAuditoriaLugares frmaudlugares=new FrmAuditoriaLugares();
        escritorio.add(frmaudlugares);
        frmaudlugares.show();
      
    }//GEN-LAST:event_jMenuItem46ActionPerformed

    private void jMenuItem50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem50ActionPerformed
        FrmAuditoriaResoluciones frmaudres=new FrmAuditoriaResoluciones();
        escritorio.add(frmaudres);
        frmaudres.show();
      
    }//GEN-LAST:event_jMenuItem50ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        FrmRegistroPersonas frmregper=new FrmRegistroPersonas();
        escritorio.add(frmregper);
        frmregper.show();
     
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem48ActionPerformed
        FrmAuditoriaPersonaAudiencia frmaudper=new FrmAuditoriaPersonaAudiencia();
        escritorio.add(frmaudper);
        frmaudper.show();
        
    }//GEN-LAST:event_jMenuItem48ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        FrmRegistroAbogados frmregab=new FrmRegistroAbogados();
        escritorio.add(frmregab);
        frmregab.show();
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        FrmAuditoriaAbogados frmaudabogados=new FrmAuditoriaAbogados();
        escritorio.add(frmaudabogados);
        frmaudabogados.show();
       
    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        FrmConsultaAbogados consulta=new FrmConsultaAbogados();
        escritorio.add(consulta);
        consulta.show();
        
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        FrmAuditoriaDemandados frmauddemand=new FrmAuditoriaDemandados();
        escritorio.add(frmauddemand);
        frmauddemand.show();
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        FrmDemandados frmdemand=new FrmDemandados();
        escritorio.add(frmdemand);
        frmdemand.show();
       
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        FrmPersonasDemandadas frmper=new FrmPersonasDemandadas();
        escritorio.add(frmper);
        frmper.show();
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        FrmEmpresaDemandada frmemp=new FrmEmpresaDemandada();
        escritorio.add(frmemp);
        frmemp.show();
        
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem49ActionPerformed
        FrmAuditoriaPersonaDemandada frmaudper=new FrmAuditoriaPersonaDemandada();
        escritorio.add(frmaudper);
        frmaudper.show();
      
    }//GEN-LAST:event_jMenuItem49ActionPerformed

    private void jMenuItem42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem42ActionPerformed
        FrmAuditoriaEmpresaDemandada frmaudemp=new FrmAuditoriaEmpresaDemandada();
        escritorio.add(frmaudemp);
        frmaudemp.show();
        
    }//GEN-LAST:event_jMenuItem42ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrmRegistroPersonasDemandadas frmper=new FrmRegistroPersonasDemandadas();
        escritorio.add(frmper);
        frmper.show();
      
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        FrmRegsitroEmpresasDemandadas frmemp=new FrmRegsitroEmpresasDemandadas();
        escritorio.add(frmemp);
        frmemp.show();
       
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        FrmRegistroAsunto frmrega=new FrmRegistroAsunto();
        escritorio.add(frmrega);
        frmrega.show();
        
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        FrmAuditoriaAsuntos frmauda=new FrmAuditoriaAsuntos();
        escritorio.add(frmauda);
        frmauda.show();
    
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        FrmAsuntoAbogado frmasunto=new FrmAsuntoAbogado();
        escritorio.add(frmasunto);
        frmasunto.show();
        
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
       FrmAuditoriaAsuntoAbogado frmaudasunto=new FrmAuditoriaAsuntoAbogado();
       escritorio.add(frmaudasunto);
       frmaudasunto.show();
       
    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        FrmRegistroAudiencia frmregaud=new FrmRegistroAudiencia();
        escritorio.add(frmregaud);
        frmregaud.show();
       
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        FrmAuditoriaAudiencias frmaud=new FrmAuditoriaAudiencias();
        escritorio.add(frmaud);
        frmaud.show();
        
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        FrmRegistroAsesoria frmregaud=new FrmRegistroAsesoria();
        escritorio.add(frmregaud);
        frmregaud.show();
    
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        FrmAuditoriaAsesoria frmaudase=new FrmAuditoriaAsesoria();
        escritorio.add(frmaudase);
        frmaudase.show();
     
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        FrmRegistroPersonasAudiencias frmregperaud=new FrmRegistroPersonasAudiencias();
        escritorio.add(frmregperaud);
        frmregperaud.show();
  
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
       FrmAuditoriaAsistenciaPersonas frmaudper=new FrmAuditoriaAsistenciaPersonas();
       escritorio.add(frmaudper);
       frmaudper.show();
       
    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        FrmPersonasRegistradas frmper=new FrmPersonasRegistradas();
        escritorio.add(frmper);
        frmper.show();
       
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        FrmTipoMedio ftm=new FrmTipoMedio();
       escritorio.add(ftm);
       ftm.show();
     
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        FrmMediosContacto fmc=new FrmMediosContacto();
        escritorio.add(fmc);
        fmc.show();
     
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        FrmRegistroNuevoUsuario frmnvouser=new FrmRegistroNuevoUsuario();
        escritorio.add(frmnvouser);
        frmnvouser.show();
    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        FrmModificarUsuario frmmoduser=new FrmModificarUsuario();
        escritorio.add(frmmoduser);
        frmmoduser.show();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrmNuevoRegistroContacto frmnvocontacto=new FrmNuevoRegistroContacto();
        escritorio.add(frmnvocontacto);
        frmnvocontacto.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JMenu jMasOpciones;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    public javax.swing.JMenu jMenuAbogado;
    public javax.swing.JMenu jMenuAsunto;
    public javax.swing.JMenu jMenuAudiencia;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenu jMenuClientes;
    public javax.swing.JMenu jMenuDemandados;
    public javax.swing.JMenu jMenuEstado;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JMenuItem jMenuItem42;
    private javax.swing.JMenuItem jMenuItem43;
    private javax.swing.JMenuItem jMenuItem44;
    private javax.swing.JMenuItem jMenuItem45;
    private javax.swing.JMenuItem jMenuItem46;
    private javax.swing.JMenuItem jMenuItem47;
    private javax.swing.JMenuItem jMenuItem48;
    private javax.swing.JMenuItem jMenuItem49;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem50;
    private javax.swing.JMenuItem jMenuItem51;
    private javax.swing.JMenuItem jMenuItem52;
    private javax.swing.JMenuItem jMenuItem53;
    private javax.swing.JMenuItem jMenuItem54;
    private javax.swing.JMenuItem jMenuItem55;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public javax.swing.JMenu jMenuLugares;
    public javax.swing.JMenu jMenuPersonas;
    public javax.swing.JMenu jMenuResolucion;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbl_usuario;
    // End of variables declaration//GEN-END:variables
}
